### ISSUE TITLE
Printen van kaart

### ISSUE THREAD

**Issue by Geoneer** [Geoneer/KPN-Geoexplorer#2]
http://www.geo-solutions.it/blog/developers-corner-advanced-usage-of-geoserver-print-plugin/

**Comment by Geoneer** [comment]
http://docs.geoserver.org/latest/en/user/extensions/printing/index.html

**Comment by Geoneer** [comment]
GeoServer should create a print module configuration file in GEOSERVER_DATA_DIR/printing/config.yaml. Checking for this file’s existence is a quick way to verify the module is installed properly. 

Deze staat hier: d:\Tcat_8\webapps\geoserver\data\printing\config.yaml

**Comment by Geoneer** [comment]
#===========================================================================
# allowed DPIs
#===========================================================================
dpis: [75, 150, 300]

#===========================================================================
# the allowed scales
#===========================================================================
scales:
  - 25000
  - 50000
  - 100000
  - 200000
  - 500000
  - 1000000
  - 2000000
  - 4000000

#===========================================================================
# the list of allowed hosts
#===========================================================================
hosts:
  - !localMatch
    dummy: true
  - !ipMatch
    ip: www.camptocamp.org
  - !dnsMatch
    host: demo.opengeo.org
    port: 80
  - !dnsMatch
    host: terraservice.net
    port: 80
  - !dnsMatch
    host: sigma.openplans.org
  - !dnsMatch
    host: demo.mapfish.org

layouts:
  Legal:
    mainPage:
      pageSize: LEGAL
      items:
        - !map
          spacingAfter: 30
          width: 440
          height: 483
  #===========================================================================
  A4 portrait:
  #===========================================================================
    metaData:
#      title: '${mapTitle}'
      author: 'MapFish print module'
      subject: 'Simple layout'
      keywords: 'map,print'
      creator: 'MapFish'

    titlePage:
      pageSize: A4
      items:
        - !text
          spacingAfter: 150
        - !text
          font: Helvetica
          fontSize: 40
          spacingAfter: 100
          align: center
          text: '${layout}'
        - !image
          maxWidth: 160
          maxHeight: 160
          spacingAfter: 100
          align: center
          url: http://trac.mapfish.org/trac/mapfish/attachment/ticket/3/logo_v8_sphere.svg?format=raw

      footer: &commonFooter
        height: 30
        items:
          - !columns
            config:
              cells:
                - paddingBottom: 5   
            items:
              - !text
                backgroundColor: #FF0000
                align: left
                text: a red box
              - !text
                align: right
                text: 'Page ${pageNum}'
              - !image
                align: center
                maxWidth: 100
                maxHeight: 30
                spacingAfter: 200
                url: 'http://geoserver.org/img/geoserver-logo.png'

    #-------------------------------------------------------------------------
    mainPage:
      pageSize: A4
      rotation: true
#      header:
#        height: 50
#        items:
#          - !text
#            font: Helvetica
#            fontSize: 30
#            align: right
#            text: '${layout}'
      items:
        - !text
          text: '${mapTitle}'
          fontSize: 30
          spacingAfter: 30
        - !map
          spacingAfter: 30
          width: 440
          height: 483
        - !columns
          # columns can have an absolute position. In that case, they need the 3 following fields:
          absoluteX: 410
          absoluteY: 310
          width: 100
          items:
            - !scalebar
              type: bar
              maxSize: 100
              barBgColor: white
              fontSize: 8
              align: right
        - !text
          text: '${comment}'
          spacingAfter: 30
        - !attributes
          source: data
          spacingAfter: 30
          columnDefs:
            id:
              columnWeight: 2
              header: !text
                text: ID
                backgroundColor: #A0A0A0
              cell: !text
                text: '${id}'
            name:
              columnWeight: 5
              header: !text
                text: Name
                backgroundColor: #A0A0A0
              cell: !columns
                config:
                  cells:
                    - backgroundColor: '${nameBackgroundColor}'
                      borderWidth: 1
                      borderColor: '${nameBorderColor}'
                items:
                  - !text
                    text: '${name}'
            icon:
              columnWeight: 2
              header: !text
                text: Symbol
                backgroundColor: #A0A0A0
              cell: !image
                align: center
                maxWidth: 15
                maxHeight: 15
                url: 'http://www.mapfish.org/svn/mapfish/trunk/MapFish/client/mfbase/mapfish/img/${icon}.png'
        - !text
          font: Helvetica
          fontSize: 9
          align: right
          text: '1:${scale} ${now MM.dd.yyyy}'
      footer: *commonFooter

**Comment by Geoneer** [comment]
![image](https://cloud.githubusercontent.com/assets/218929/8269496/3a97bcd6-17ab-11e5-9746-1f8ee3dacc00.png)

**Comment by Geoneer** [comment]
Geen print preview in beeld op de test pagina:

![image](https://cloud.githubusercontent.com/assets/218929/8269517/4a203204-17ac-11e5-8f9b-65196a2cba45.png)

**Comment by Geoneer** [comment]
hier print plugin ophalen zoals beschreven in Mastering Geoserver:

http://ares.boundlessgeo.com/geoserver/2.6.x/ext-latest/geoserver-2.6-SNAPSHOT-printing-plugin.zip

**Comment by Geoneer** [comment]
restart tomcat

![image](https://cloud.githubusercontent.com/assets/218929/8269590/639e5de2-17b0-11e5-9a28-a801c1b2420a.png)

**Comment by Geoneer** [comment]
check in Geoserver - Demos of de printmodule actief is:

![image](https://cloud.githubusercontent.com/assets/218929/8269603/01fcdbda-17b1-11e5-98f3-ce01dc1885b7.png)

**Comment by Geoneer** [comment]
met topp:states als een layer krijg ik beeld:

![image](https://cloud.githubusercontent.com/assets/218929/8269619/2c2b5e30-17b2-11e5-8ffe-7b3473f064a0.png)

**Comment by Geoneer** [comment]
[print]

![image](https://cloud.githubusercontent.com/assets/218929/8269624/7d6ca196-17b2-11e5-8c2b-396e668823c0.png)

![image](https://cloud.githubusercontent.com/assets/218929/8269626/8d9f568a-17b2-11e5-8a58-7ae79244b74c.png)

**Comment by Geoneer** [comment]
in de Geoserver komt er .pdf uit. Nu kijken of dit vanuit Geoexplorer ook werkt.

**Comment by Geoneer** [comment]
http://gis.stackexchange.com/questions/74021/how-can-i-print-openlayers-with-base-osm-and-geoserver-wms-layers

**Comment by Geoneer** [comment]
http://geoext.org/lib/GeoExt/data/PrintProvider.html

**Comment by Geoneer** [comment]
![image](https://cloud.githubusercontent.com/assets/218929/8269742/f2706e10-17b6-11e5-8157-78fb9d69816b.png)

**Comment by Geoneer** [comment]
geen resultaat:

![image](https://cloud.githubusercontent.com/assets/218929/8269749/55ef90d8-17b7-11e5-9ae5-daf5a7ab2ff5.png)


debuggen en uitzoeken wat hiervan de oorzaak is. GeoExplorer en Geoserver zijn op zelfde domein + poort. Wat is de oorzaak van deze melding? Uitzoeken en kijken hoe dit op te lossen is.

**Comment by Geoneer** [comment]
"Error while generating PDF:
org.mapfish.print.InvalidValueException: url has an invalid value: http://geoserver.org/img/geoserver-logo.png
	at org.mapfish.print.PDFUtils.createImage(PDFUtils.java:668)
	at org.mapfish.print.PDFUtils.createImageChunk(PDFUtils.java:656)
	at org.mapfish.print.PDFUtils.createImageChunk(PDFUtils.java:653)
	at org.mapfish.print.config.layout.ImageBlock.render(ImageBlock.java:66)
	at org.mapfish.print.PDFUtils.createCell(PDFUtils.java:624)
	at org.mapfish.print.PDFUtils.buildTable(PDFUtils.java:609)
	at org.mapfish.print.config.layout.ColumnsBlock.render(ColumnsBlock.java:72)
	at org.mapfish.print.PDFUtils.createCell(PDFUtils.java:624)
	at org.mapfish.print.PDFUtils.buildTable(PDFUtils.java:609)
	at org.mapfish.print.config.layout.HeaderFooter.render(HeaderFooter.java:55)
	at org.mapfish.print.PDFCustomBlocks.addFooter(PDFCustomBlocks.java:134)
	at org.mapfish.print.PDFCustomBlocks.onEndPage(PDFCustomBlocks.java:89)
	at com.itextpdf.text.pdf.PdfDocument.newPage(PdfDocument.java:911)
	at com.itextpdf.text.Document.newPage(Document.java:363)
	at org.mapfish.print.config.layout.Page.render(Page.java:63)
	at org.mapfish.print.config.layout.MainPage.render(MainPage.java:63)
	at org.mapfish.print.config.layout.Layout.render(Layout.java:59)
	at org.mapfish.print.output.AbstractOutputFormat.doPrint(AbstractOutputFormat.java:30)
	at org.mapfish.print.output.PdfOutputFactory.print(PdfOutputFactory.java:58)
	at org.mapfish.print.MapPrinter.print(MapPrinter.java:173)
	at org.mapfish.print.servlet.MapPrinterServlet.doCreatePDFFile(MapPrinterServlet.java:366)
	at org.mapfish.print.servlet.MapPrinterServlet.createPDF(MapPrinterServlet.java:184)
	at org.mapfish.print.servlet.MapPrinterServlet.doPost(MapPrinterServlet.java:112)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.springframework.web.servlet.mvc.ServletWrappingController.handleRequestInternal(ServletWrappingController.java:159)
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153)
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:923)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:789)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.geoserver.filters.ThreadLocalsCleanupFilter.doFilter(ThreadLocalsCleanupFilter.java:28)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:75)
	at org.geoserver.wms.animate.AnimatorFilter.doFilter(AnimatorFilter.java:71)
	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:71)
	at org.geoserver.monitor.MonitorFilter.doFilter(MonitorFilter.java:138)
	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:71)
	at org.geoserver.filters.SpringDelegatingFilter.doFilter(SpringDelegatingFilter.java:46)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.geoserver.platform.AdvancedDispatchFilter.doFilter(AdvancedDispatchFilter.java:50)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:311)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:116)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
	at org.geoserver.security.filter.GeoServerAnonymousAuthenticationFilter.doFilter(GeoServerAnonymousAuthenticationFilter.java:54)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:150)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
	at org.geoserver.security.filter.GeoServerBasicAuthenticationFilter.doFilter(GeoServerBasicAuthenticationFilter.java:83)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
	at org.geoserver.security.filter.GeoServerSecurityContextPersistenceFilter$1.doFilter(GeoServerSecurityContextPersistenceFilter.java:53)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:173)
	at org.geoserver.security.GeoServerSecurityFilterChainProxy.doFilter(GeoServerSecurityFilterChainProxy.java:135)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.geoserver.filters.LoggingFilter.doFilter(LoggingFilter.java:76)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.geoserver.filters.GZIPFilter.doFilter(GZIPFilter.java:42)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.geoserver.filters.SessionDebugFilter.doFilter(SessionDebugFilter.java:48)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.geoserver.filters.FlushSafeFilter.doFilter(FlushSafeFilter.java:44)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.vfny.geoserver.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:109)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:617)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1521)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1478)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Circular redirect to 'http://geoserver.org:80/img/geoserver-logo.png'
	at org.mapfish.print.PDFUtils.handleImageLoadError(PDFUtils.java:357)
	at org.mapfish.print.PDFUtils.loadImageFromUrl(PDFUtils.java:341)
	at org.mapfish.print.PDFUtils.getImageDirect(PDFUtils.java:182)
	at org.mapfish.print.PDFUtils.getImage(PDFUtils.java:102)
	at org.mapfish.print.PDFUtils.createImage(PDFUtils.java:666)
	... 115 more
"

**Comment by Geoneer** [comment]
![image](https://cloud.githubusercontent.com/assets/218929/8271757/1b7af930-1828-11e5-9674-17f6fdd2273d.png)

Is het de achtergrondkaart van MapQuest?

**Comment by Geoneer** [comment]
met alleen de laag CGB krijg nog fout:

![image](https://cloud.githubusercontent.com/assets/218929/8271772/b00cc524-1828-11e5-8ec1-f22d153d94f2.png)

**Comment by Geoneer** [comment]
https://www.google.nl/search?q=org.mapfish.print.InvalidValueException%3A+url+has+an+invalid+value%3A+http%3A%2F%2Fgeoserver.org%2Fimg%2Fgeoserver-logo.png&oq=org.mapfish.print.InvalidValueException%3A+url+has+an+invalid+value%3A+http%3A%2F%2Fgeoserver.org%2Fimg%2Fgeoserver-logo.png&aqs=chrome..69i57.1149j0j7&sourceid=chrome&es_sm=0&ie=UTF-8

**Comment by Geoneer** [comment]
![image](https://cloud.githubusercontent.com/assets/218929/8271794/247d6610-182a-11e5-8c56-6cba5f10998c.png)

**Comment by Geoneer** [comment]
ok. de config.yaml aanpassen...

**Comment by Geoneer** [comment]
de url van het logo was het probleem. Er wordt nu een .pdf gemaakt van de kaart. Deze kaart nu nog stylen. <new issue>

**Comment by Geoneer** [comment]
config.yaml:

#===========================================================================
# allowed DPIs
#===========================================================================
dpis: [75, 150, 300]

#===========================================================================
# the allowed scales
#===========================================================================
scales:
  - 25000
  - 50000
  - 100000
  - 200000
  - 500000
  - 1000000
  - 2000000
  - 4000000

#===========================================================================
# the list of allowed hosts
#===========================================================================
hosts:
  - !localMatch
    dummy: true
  - !ipMatch
    ip: www.camptocamp.org
  - !dnsMatch
    host: demo.opengeo.org
    port: 80
  - !dnsMatch
    host: terraservice.net
    port: 80
  - !dnsMatch
    host: sigma.openplans.org
  - !dnsMatch
    host: demo.mapfish.org

layouts:
  Legal:
    mainPage:
      pageSize: LEGAL
      items:
        - !map
          spacingAfter: 30
          width: 440
          height: 483
  #===========================================================================
  A4 portrait:
  #===========================================================================
    metaData:
#      title: '${mapTitle}'
      author: 'MapFish print module'
      subject: 'Simple layout'
      keywords: 'map,print'
      creator: 'MapFish'

    titlePage:
      pageSize: A4
      items:
        - !text
          spacingAfter: 150
        - !text
          font: Helvetica
          fontSize: 40
          spacingAfter: 100
          align: center
          text: '${layout}'
        - !image
          maxWidth: 160
          maxHeight: 160
          spacingAfter: 100
          align: center
          url: http://trac.mapfish.org/trac/mapfish/attachment/ticket/3/logo_v8_sphere.svg?format=raw

      footer: &commonFooter
        height: 30
        items:
          - !columns
            config:
              cells:
                - paddingBottom: 5   
            items:
              - !text
                backgroundColor: #FF0000
                align: left
                text: a red box
              - !text
                align: right
                text: 'Page ${pageNum}'
              - !image
                align: center
                maxWidth: 100
                maxHeight: 30
                spacingAfter: 200
                url: 'http://www.kpn.com/ss/Satellite/yavUnLl8hN7yMh6Gh2IPWqYD60HbUkXsNK4iD8PcUpR0bnBXyZZtwQUuCgSUG72CJE/MungoBlobs/kpn_logo.png'

    #-------------------------------------------------------------------------
    mainPage:
      pageSize: A4
      rotation: true
#      header:
#        height: 50
#        items:
#          - !text
#            font: Helvetica
#            fontSize: 30
#            align: right
#            text: '${layout}'
      items:
        - !text
          text: '${mapTitle}'
          fontSize: 30
          spacingAfter: 30
        - !map
          spacingAfter: 30
          width: 440
          height: 483
        - !columns
          # columns can have an absolute position. In that case, they need the 3 following fields:
          absoluteX: 410
          absoluteY: 310
          width: 100
          items:
            - !scalebar
              type: bar
              maxSize: 100
              barBgColor: white
              fontSize: 8
              align: right
        - !text
          text: '${comment}'
          spacingAfter: 30
        - !attributes
          source: data
          spacingAfter: 30
          columnDefs:
            id:
              columnWeight: 2
              header: !text
                text: ID
                backgroundColor: #A0A0A0
              cell: !text
                text: '${id}'
            name:
              columnWeight: 5
              header: !text
                text: Name
                backgroundColor: #A0A0A0
              cell: !columns
                config:
                  cells:
                    - backgroundColor: '${nameBackgroundColor}'
                      borderWidth: 1
                      borderColor: '${nameBorderColor}'
                items:
                  - !text
                    text: '${name}'
            icon:
              columnWeight: 2
              header: !text
                text: Symbol
                backgroundColor: #A0A0A0
              cell: !image
                align: center
                maxWidth: 15
                maxHeight: 15
                url: 'http://www.mapfish.org/svn/mapfish/trunk/MapFish/client/mfbase/mapfish/img/${icon}.png'
        - !text
          font: Helvetica
          fontSize: 9
          align: right
          text: '1:${scale} ${now MM.dd.yyyy}'
      footer: *commonFooter

**Comment by Geoneer** [comment]
http://geoext.github.io/geoext2/examples/printpreview/print-preview.html

**Comment by Geoneer** [comment]
http://gis.stackexchange.com/questions/74021/how-can-i-print-openlayers-with-base-osm-and-geoserver-wms-layers

**Comment by Geoneer** [comment]
Error while generating PDF: org.mapfish.print.InvalidValueException: url has an invalid value: http://geoserver.org/img/geoserver-logo.png at 

deze fout zit in de sjabloon in de config.yaml hier:

d:\Tcat_8\webapps\geoserver\data\printing\config.yaml

![image](https://cloud.githubusercontent.com/assets/218929/8301100/5de44560-198b-11e5-8568-140d405bbe58.png)

**Comment by Geoneer** [comment]
dit werkt weer. Style van config.yaml moet worden bepaald.
